// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvcVaqRIWXdRqqbl8nOI16lnYfe0BByoE',
    appId: '1:1091671038759:web:927228e898ec4028cea702',
    messagingSenderId: '1091671038759',
    projectId: 'nti6-38c02',
    authDomain: 'nti6-38c02.firebaseapp.com',
    storageBucket: 'nti6-38c02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXrztjLrZrJLp6tIdOLJ6gs-34Mj9NAQw',
    appId: '1:1091671038759:android:cd62d7db7ed14f3bcea702',
    messagingSenderId: '1091671038759',
    projectId: 'nti6-38c02',
    storageBucket: 'nti6-38c02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM79iFEcqhxRxiIYfQ3Kai5kLsVFbf2JM',
    appId: '1:1091671038759:ios:a3021ee68bfc1747cea702',
    messagingSenderId: '1091671038759',
    projectId: 'nti6-38c02',
    storageBucket: 'nti6-38c02.firebasestorage.app',
    iosBundleId: 'com.example.tempmealapp',
  );
}
